export default {
  '=': 'an assignment operator \'=\'',
  '+': 'an addition operator \'+\'',
  '-': 'a subtraction operator \'-\'',
  '*': 'a multiplication operator \'*\'',
  '/': 'a division operator \'/\'',
  '{': 'an opening brace \'{\'',
  '}': 'a closing brace \'}\'',
  '(': 'an opening paren \'(\'',
  ')': 'a closing paren \')\'',
  '[': 'an opening bracket \'[\'',
  ']': 'a closing bracket \']\'',
  '<': 'an opening pointy bracket \'<\'',
  '>': 'a closing pointy bracket \'>\'',
  '@': 'a decorator operator \'@\'',
  ',': 'a comma \',\'',
};
